/**
 * OrbitDock — Quick-access floating layer for Orbit skills.
 *
 * Renders a fixed FAB (bottom-right, stacked above OrbitChatFAB) that opens
 * a side panel (desktop) or bottom sheet (mobile) with context-aware skill
 * suggestions and the current system cognitive/emotional state.
 *
 * Suggestions are generated by `getOrbitSuggestions` using real emotional
 * state, cognitive style, recent chat messages, and session action history.
 * Each suggestion carries a `confidence` score rendered as an inline bar.
 * Actions route through `useOrbit.runSuggestion` → `useOrbitSignalStore` →
 * `OrbitChatFAB` which fires the prompt into SmartChat.
 *
 * MD3 Gold Compliant — no hardcoded colours, spacing, or z-index values.
 */

import React, { useState, useCallback, useEffect, useRef } from 'react';
import Box           from '@mui/material/Box';
import Drawer        from '@mui/material/Drawer';
import Fab           from '@mui/material/Fab';
import Tooltip       from '@mui/material/Tooltip';
import IconButton    from '@mui/material/IconButton';
import Typography    from '@mui/material/Typography';
import Button        from '@mui/material/Button';
import Chip          from '@mui/material/Chip';
import Divider       from '@mui/material/Divider';
import useMediaQuery from '@mui/material/useMediaQuery';
import { useTheme }  from '@mui/material/styles';

import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';
import CloseIcon       from '@mui/icons-material/Close';
import PsychologyIcon  from '@mui/icons-material/Psychology';
import SpeedIcon       from '@mui/icons-material/Speed';
import TipsAndUpdatesIcon from '@mui/icons-material/TipsAndUpdates';

import { useChatPrefsStore }    from '@/stores/useChatPrefsStore';
import { useConversationStore } from '@/stores/useConversationStore';
import { useOrbitSignalStore }  from '@/stores/useOrbitSignalStore';
import { useOrbit }             from '@/hooks/useOrbit';
import { getOrbitSuggestions }  from '@/modules/orbit/OrbitSuggestionEngine';
import { shouldNudge }          from '@/modules/orbit/OrbitNudgeEngine';
import { OrbitNudgeCard }       from '@/components/orbit/OrbitNudgeCard';
import type { CognitiveStyle }  from '@/modules/orchestration/CognitiveStyleEngine';
import type { EmotionalProfile } from '@/modules/orchestration/EmotionalEngine';

// ── Constants ──────────────────────────────────────────────────────────────────

/**
 * OrbitDock FAB sits above OrbitChatFAB which is already stacked above
 * FloatingSatelliteCopilot. Stack = 24 (base) + 56 (sat) + 8 + 56 (chat) + 8 = 152px.
 */
const FAB_BOTTOM = 'calc(var(--md-sys-spacing-6, 24px) + 56px + 8px + 56px + 8px)';
const FAB_RIGHT  = 'var(--md-sys-spacing-6, 24px)';

const PANEL_WIDTH  = 360;
const MOBILE_PB    = '30vh';

// ── Quick Skills ───────────────────────────────────────────────────────────────

// ── State label helpers ────────────────────────────────────────────────────────

function emotionalLabel(profile: EmotionalProfile): string {
  const map: Record<string, string> = {
    focused:      'Focalizzato',
    exploring:    'In esplorazione',
    overloaded:   'Sovraccarico',
    blocked:      'In difficoltà',
    goal_oriented: 'Orientato al goal',
  };
  return map[profile.baselineState] ?? profile.baselineState;
}

function cognitiveLabel(style: CognitiveStyle): string {
  const structMap: Record<string, string> = { low: 'fluido', medium: 'bilanciato', high: 'strutturato' };
  const speedMap:  Record<string, string> = { slow: 'riflessivo', balanced: 'equilibrato', fast: 'veloce' };
  const s = structMap[style.structure]       ?? style.structure;
  const v = speedMap[style.speedPreference]  ?? style.speedPreference;
  return `${s} / ${v}`;
}

// ── Component ──────────────────────────────────────────────────────────────────

export function OrbitDock(): React.ReactElement {
  const [open, setOpen]             = useState(false);
  const [nudgeVisible, setNudgeVisible] = useState(false);
  const [nudgeReason,  setNudgeReason]  = useState('');
  const lastNudgeRef = useRef<number>(0);

  const theme    = useTheme();
  // Mobile (<md) → bottom sheet; tablet/desktop (≥md) → right panel
  const isMobile = useMediaQuery(theme.breakpoints.down('md'));

  const { runSuggestion } = useOrbit();

  const emotionalProfile = useChatPrefsStore(s => s.emotionalProfile);
  const cognitiveStyle   = useChatPrefsStore(s => s.cognitiveStyle);

  // Real chat context — last 5 messages texts
  const getMessages    = useConversationStore(s => s.getMessages);
  const usedActionIds  = useOrbitSignalStore(s => s.usedActionIds);

  const recentMessages = getMessages()
    .slice(-5)
    .map(m => m.content)
    .filter(Boolean);

  // P44.5 — Orbit stays silent when the last assistant turn already has a decision
  const hasDecisionCard = getMessages()
    .slice(-3)
    .filter(m => m.role === 'assistant')
    .some(m => m.blocks?.some(b => b.type === 'decision_card' || b.type === 'work_session'));

  // Context-aware suggestions — recomputed each render (open state changes)
  const suggestions = getOrbitSuggestions({
    emotionalState:  emotionalProfile.baselineState,
    cognitiveStyle,
    recentMessages,
    previousActions: usedActionIds,
    hasMessages:     recentMessages.length > 0,
  });

  const handleOpen  = useCallback(() => { setOpen(true); setNudgeVisible(false); }, []);
  const handleClose = useCallback(() => setOpen(false), []);

  // ── Nudge: auto-surface top suggestion ──────────────────────────────────────
  const topSuggestion = suggestions[0];

  useEffect(() => {
    if (open) return; // panel already open — no nudge needed
    if (hasDecisionCard) return; // P44.5 — decision already surfaced, stay silent

    const decision = shouldNudge({
      emotionalState:  emotionalProfile.baselineState,
      topConfidence:   topSuggestion?.confidence,
      lastUserMessage: recentMessages.at(-1),
      msSinceLastNudge: Date.now() - lastNudgeRef.current,
    });

    if (decision.nudge) {
      lastNudgeRef.current = Date.now();
      setNudgeReason(decision.reason);
      setNudgeVisible(true);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [emotionalProfile.baselineState, recentMessages.length, open]);

  // ── Panel content ────────────────────────────────────────────────────────────

  const panelContent = (
    <Box
      role="region"
      aria-label="Orbit Dock — assistente rapido"
      sx={{
        width:          isMobile ? '100%' : PANEL_WIDTH,
        height:         '100%',
        display:        'flex',
        flexDirection:  'column',
        bgcolor:        'var(--md-sys-color-surface-container)',
        color:          'var(--md-sys-color-on-surface)',
        overflow:       'hidden',
      }}
    >
      {/* ── Header ─────────────────────────────────────────────────────────── */}
      <Box
        sx={{
          display:        'flex',
          alignItems:     'center',
          justifyContent: 'space-between',
          px:             'var(--md-sys-spacing-4, 16px)',
          py:             'var(--md-sys-spacing-3, 12px)',
          bgcolor:        'var(--md-sys-color-surface-container-high)',
          borderBottom:   '1px solid',
          borderColor:    'var(--md-sys-color-outline-variant)',
          flexShrink:     0,
        }}
      >
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 'var(--md-sys-spacing-2, 8px)' }}>
          <AutoAwesomeIcon
            aria-hidden="true"
            sx={{ color: 'var(--md-sys-color-primary)', fontSize: 'var(--md-sys-icon-size-md, 24px)' }}
          />
          <Typography
            variant="titleMedium"
            component="h2"
            sx={{
              fontWeight: 'var(--md-sys-typescale-weight-semibold)',
              color:      'var(--md-sys-color-on-surface)',
            }}
          >
            Orbit Dock
          </Typography>
        </Box>
        <IconButton
          onClick={handleClose}
          aria-label="Chiudi Orbit Dock"
          size="small"
          sx={{ color: 'var(--md-sys-color-on-surface-variant)' }}
        >
          <CloseIcon fontSize="small" aria-hidden="true" />
        </IconButton>
      </Box>

      {/* ── Scrollable body ─────────────────────────────────────────────────── */}
      <Box
        sx={{
          flex:       1,
          overflowY:  'auto',
          px:         'var(--md-sys-spacing-4, 16px)',
          py:         'var(--md-sys-spacing-4, 16px)',
          display:    'flex',
          flexDirection: 'column',
          gap:        'var(--md-sys-spacing-5, 20px)',
        }}
      >
        {/* ── Section 1: Quick Skills ─────────────────────────────────────── */}
        <Box component="section" aria-labelledby="orbit-dock-skills-heading">
          <Typography
            id="orbit-dock-skills-heading"
            variant="labelMedium"
            component="h3"
            sx={{
              color:        'var(--md-sys-color-on-surface-variant)',
              mb:           'var(--md-sys-spacing-3, 12px)',
              textTransform: 'uppercase',
              letterSpacing: '0.08em',
            }}
          >
            Suggerimenti
          </Typography>
          <Box
            sx={{
              display:       'flex',
              flexDirection: 'column',
              gap:           'var(--md-sys-spacing-2, 8px)',
            }}
          >
            {suggestions.map(s => (
              <Button
                key={s.id}
                variant="outlined"
                startIcon={<TipsAndUpdatesIcon fontSize="small" aria-hidden="true" />}
                onClick={() => {
                  runSuggestion(s);
                  handleClose();
                }}
                aria-label={s.label}
                sx={{
                  justifyContent: 'flex-start',
                  alignItems:     'flex-start',
                  flexDirection:  'column',
                  textTransform:  'none',
                  borderColor:    'var(--md-sys-color-outline-variant)',
                  color:          'var(--md-sys-color-on-surface)',
                  borderRadius:   'var(--md-sys-shape-corner-medium, 12px)',
                  py:             'var(--md-sys-spacing-2, 8px)',
                  px:             'var(--md-sys-spacing-3, 12px)',
                  fontSize:       'var(--md-sys-typescale-label-medium-font-size, 0.75rem)',
                  fontWeight:     'var(--md-sys-typescale-weight-medium)',
                  '&:hover': {
                    bgcolor:     'var(--md-sys-color-secondary-container)',
                    borderColor: 'var(--md-sys-color-secondary)',
                    color:       'var(--md-sys-color-on-secondary-container)',
                  },
                  '&:focus-visible': {
                    outline:      '2px solid',
                    outlineColor: 'var(--md-sys-color-primary)',
                    outlineOffset: 2,
                  },
                }}
              >
                <span>{s.label}</span>
                <Typography
                  variant="caption"
                  component="span"
                  sx={{
                    color:      'var(--md-sys-color-on-surface-variant)',
                    mt:         '2px',
                    textAlign:  'left',
                    whiteSpace: 'normal',
                    lineHeight: 1.3,
                  }}
                >
                  💡 {s.reason}
                </Typography>
                {/* ── Confidence bar ──────────────────────────────────────── */}
                <Box
                  role="meter"
                  aria-label={`Rilevanza: ${Math.round(s.confidence * 100)}%`}
                  aria-valuenow={Math.round(s.confidence * 100)}
                  aria-valuemin={0}
                  aria-valuemax={100}
                  sx={{
                    mt:           'var(--md-sys-spacing-1, 4px)',
                    width:        '100%',
                    height:       '3px',
                    borderRadius: '2px',
                    bgcolor:      'var(--md-sys-color-surface-container-highest)',
                    overflow:     'hidden',
                  }}
                >
                  <Box
                    sx={{
                      height:  '100%',
                      width:   `${Math.round(s.confidence * 100)}%`,
                      bgcolor: s.confidence >= 0.85
                        ? 'var(--md-sys-color-primary)'
                        : s.confidence >= 0.70
                          ? 'var(--md-sys-color-secondary)'
                          : 'var(--md-sys-color-tertiary)',
                      borderRadius: '2px',
                      transition:   'width 0.4s ease',
                    }}
                  />
                </Box>
              </Button>
            ))}
          </Box>
        </Box>

        <Divider sx={{ borderColor: 'var(--md-sys-color-outline-variant)' }} />

        {/* ── Section 2: System State ─────────────────────────────────────── */}
        <Box component="section" aria-labelledby="orbit-dock-state-heading">
          <Typography
            id="orbit-dock-state-heading"
            variant="labelMedium"
            component="h3"
            sx={{
              color:        'var(--md-sys-color-on-surface-variant)',
              mb:           'var(--md-sys-spacing-3, 12px)',
              textTransform: 'uppercase',
              letterSpacing: '0.08em',
            }}
          >
            Stato sistema
          </Typography>
          <Box
            sx={{
              display:       'flex',
              flexDirection: 'column',
              gap:           'var(--md-sys-spacing-2, 8px)',
            }}
          >
            {/* Emotional state */}
            <Box
              sx={{
                display:       'flex',
                alignItems:    'center',
                justifyContent: 'space-between',
                bgcolor:       'var(--md-sys-color-surface-container-lowest)',
                borderRadius:  'var(--md-sys-shape-corner-small, 8px)',
                px:            'var(--md-sys-spacing-3, 12px)',
                py:            'var(--md-sys-spacing-2, 8px)',
              }}
            >
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 'var(--md-sys-spacing-2, 8px)' }}>
                <PsychologyIcon
                  aria-hidden="true"
                  sx={{
                    color:    'var(--md-sys-color-tertiary)',
                    fontSize: 'var(--md-sys-icon-size-sm, 20px)',
                  }}
                />
                <Typography
                  variant="bodySmall"
                  sx={{ color: 'var(--md-sys-color-on-surface-variant)' }}
                >
                  Stato emotivo
                </Typography>
              </Box>
              <Chip
                label={emotionalLabel(emotionalProfile)}
                size="small"
                sx={{
                  bgcolor:   'var(--md-sys-color-tertiary-container)',
                  color:     'var(--md-sys-color-on-tertiary-container)',
                  fontWeight: 'var(--md-sys-typescale-weight-medium)',
                  fontSize:  'var(--md-sys-typescale-label-small-font-size, 0.688rem)',
                }}
              />
            </Box>

            {/* Cognitive style */}
            <Box
              sx={{
                display:       'flex',
                alignItems:    'center',
                justifyContent: 'space-between',
                bgcolor:       'var(--md-sys-color-surface-container-lowest)',
                borderRadius:  'var(--md-sys-shape-corner-small, 8px)',
                px:            'var(--md-sys-spacing-3, 12px)',
                py:            'var(--md-sys-spacing-2, 8px)',
              }}
            >
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 'var(--md-sys-spacing-2, 8px)' }}>
                <SpeedIcon
                  aria-hidden="true"
                  sx={{
                    color:    'var(--md-sys-color-secondary)',
                    fontSize: 'var(--md-sys-icon-size-sm, 20px)',
                  }}
                />
                <Typography
                  variant="bodySmall"
                  sx={{ color: 'var(--md-sys-color-on-surface-variant)' }}
                >
                  Stile cognitivo
                </Typography>
              </Box>
              <Chip
                label={cognitiveLabel(cognitiveStyle)}
                size="small"
                sx={{
                  bgcolor:   'var(--md-sys-color-secondary-container)',
                  color:     'var(--md-sys-color-on-secondary-container)',
                  fontWeight: 'var(--md-sys-typescale-weight-medium)',
                  fontSize:  'var(--md-sys-typescale-label-small-font-size, 0.688rem)',
                }}
              />
            </Box>
          </Box>
        </Box>
      </Box>
    </Box>
  );

  return (
    <>
      {/* ── FAB trigger ─────────────────────────────────────────────────────── */}
      <Tooltip title="Apri assistente rapido" placement="left" arrow>
        <Fab
          onClick={handleOpen}
          aria-label="Apri Orbit Dock — assistente rapido"
          aria-expanded={open}
          aria-haspopup="dialog"
          size="medium"
          sx={{
            position:  'fixed',
            bottom:    FAB_BOTTOM,
            right:     FAB_RIGHT,
            zIndex:    'calc(var(--md-sys-z-modal, 1300) - 1)',
            bgcolor:   'var(--md-sys-color-tertiary)',
            color:     'var(--md-sys-color-on-tertiary)',
            boxShadow: 'var(--md-sys-elevation-level3)',
            transition: 'transform 200ms cubic-bezier(0.2, 0, 0, 1)',
            '&:hover': {
              bgcolor:   'var(--md-sys-color-tertiary)',
              transform: 'scale(1.05)',
            },
            '&:focus-visible': {
              outline:      '2px solid',
              outlineColor: 'var(--md-sys-color-tertiary)',
              outlineOffset: 3,
            },
          }}
        >
          <AutoAwesomeIcon
            aria-hidden="true"
            sx={{ fontSize: 'var(--md-sys-icon-size-md, 24px)' }}
          />
        </Fab>
      </Tooltip>

      {/* ── Panel overlay ───────────────────────────────────────────────────── */}
      <Drawer
        anchor={isMobile ? 'bottom' : 'right'}
        open={open}
        onClose={handleClose}
        aria-label="Orbit Dock — pannello assistente rapido"
        ModalProps={{
          keepMounted: false,
        }}
        PaperProps={{
          elevation: 0,
          sx: {
            width:        isMobile ? '100%' : PANEL_WIDTH,
            height:       isMobile ? MOBILE_PB : '100%',
            borderRadius: isMobile
              ? 'var(--md-sys-shape-corner-extra-large, 28px) var(--md-sys-shape-corner-extra-large, 28px) 0 0'
              : 0,
            bgcolor:      'var(--md-sys-color-surface-container)',
            overflow:     'hidden',
          },
        }}
        sx={{
          zIndex: 'var(--md-sys-z-modal, 1300)',
          '& .MuiDrawer-paper': {
            // slide-in transition is handled by MUI Drawer by default;
            // extra fade via opacity for the panel content
            animation: open ? 'orbit-dock-fadein 180ms ease-out both' : undefined,
          },
          '@keyframes orbit-dock-fadein': {
            from: { opacity: 0 },
            to:   { opacity: 1 },
          },
        }}
      >
        {panelContent}
      </Drawer>

      {/* ── Proactive nudge card ─────────────────────────────────────────────── */}
      <OrbitNudgeCard
        visible={nudgeVisible && !open}
        reason={nudgeReason}
        suggestion={topSuggestion}
        onAccept={() => {
          if (topSuggestion) runSuggestion(topSuggestion);
          setNudgeVisible(false);
        }}
        onDismiss={() => {
          setNudgeVisible(false);
          // Record a short cooldown so the nudge doesn't immediately resurface
          lastNudgeRef.current = Date.now();
        }}
      />
    </>
  );
}

export default OrbitDock;
